"""Realistic mock emails for demo mode — no Outlook access needed."""

from datetime import datetime, timedelta, timezone

_now = datetime.now(timezone.utc)


def _ts(hours_ago: float) -> str:
    return (_now - timedelta(hours=hours_ago)).strftime("%Y-%m-%dT%H:%M:%SZ")


MOCK_EMAILS: list[dict] = [
    # ── MGM Customer Emails ──
    {
        "id": "demo-001",
        "subject": "URGENT: MGM Resorts — SSO integration down in production",
        "from": "sre-alerts@cisco.com",
        "from_name": "SRE Alerts",
        "received": _ts(0.5),
        "body_preview": "Multiple monitors firing for the MGM Resorts SSO gateway. SAML assertion validation failing for all MGM properties since 06:47 UTC. 503 error rate spiked to 42%. On-call team is investigating. All hands needed for triage call at 07:00 UTC. Bridge link: https://webex.cisco.com/meet/incident-2847",
        "body": "",
        "importance": "high",
        "is_read": False,
        "has_attachments": False,
    },
    {
        "id": "demo-002",
        "subject": "Re: MGM Q3 Quarterly Business Review — deck feedback needed by EOD",
        "from": "sarah.chen@cisco.com",
        "from_name": "Sarah Chen",
        "received": _ts(2.0),
        "body_preview": "Hi team, I've updated the MGM QBR deck with the latest pipeline numbers. Can everyone review slides 12-18 (MGM customer success metrics and renewal forecast) and send comments by 5pm PT today? We present to the VP tomorrow at 9am. The slide on MGM renewal rates needs the most attention — numbers look off.",
        "body": "",
        "importance": "normal",
        "is_read": False,
        "has_attachments": True,
    },
    {
        "id": "demo-011",
        "subject": "Re: Re: MGM QBR — still waiting on your slides feedback",
        "from": "sarah.chen@cisco.com",
        "from_name": "Sarah Chen",
        "received": _ts(1.0),
        "body_preview": "Hey, following up again on the MGM QBR deck. I haven't heard back from you yet and the VP presentation is TOMORROW at 9am. I really need your input on slides 12-18 ASAP. The MGM renewal rate numbers are still wrong and I can't fix them without your data. Please prioritize this.",
        "body": "",
        "importance": "high",
        "is_read": False,
        "has_attachments": False,
    },
    {
        "id": "demo-014",
        "subject": "UPDATE: MGM SSO outage — error rate still at 28%, RCA in progress",
        "from": "sre-alerts@cisco.com",
        "from_name": "SRE Alerts",
        "received": _ts(0.2),
        "body_preview": "Update on MGM incident INC-2847: Error rate reduced from 42% to 28% after load balancer config change. Root cause identified as misconfigured rate limiter after last deploy to MGM SSO cluster. Fix deployed to staging, awaiting MGM prod approval. ETA to full recovery: 90 minutes.",
        "body": "",
        "importance": "high",
        "is_read": False,
        "has_attachments": False,
    },
    {
        "id": "demo-016",
        "subject": "MGM Resorts — license true-up discussion before renewal",
        "from": "david.martinez@mgmresorts.com",
        "from_name": "David Martinez (MGM)",
        "received": _ts(5.0),
        "body_preview": "Hi team, as we approach the August renewal window, we'd like to schedule a meeting to discuss the license true-up. Our actual seat count is about 15% under the contracted amount and we want to right-size before renewal. Can someone from your team hop on a call next week? We're also evaluating a competitor proposal.",
        "body": "",
        "importance": "normal",
        "is_read": False,
        "has_attachments": True,
    },
    # ── Providence Customer Emails ──
    {
        "id": "demo-017",
        "subject": "Providence Health — HIPAA compliance audit findings for Cisco integration",
        "from": "jennifer.wu@providence.org",
        "from_name": "Jennifer Wu (Providence)",
        "received": _ts(1.8),
        "body_preview": "Hi, our annual HIPAA compliance audit flagged 3 items related to the Cisco Webex integration with our EHR system. We need remediation plans for: (1) PHI data at rest encryption gaps, (2) access logging inconsistencies, (3) session timeout configuration. Audit response due by June 15. Can we schedule a call this week?",
        "body": "",
        "importance": "high",
        "is_read": False,
        "has_attachments": True,
    },
    {
        "id": "demo-018",
        "subject": "Re: Providence telehealth deployment — Phase 2 timeline slip",
        "from": "mark.thompson@cisco.com",
        "from_name": "Mark Thompson",
        "received": _ts(3.5),
        "body_preview": "Bad news — the Providence telehealth Phase 2 rollout is slipping by 2 weeks. The API integration with their Epic EHR is hitting authentication issues. Providence's IT team needs us to support their SMART on FHIR implementation. They're frustrated because this was supposed to go live for 12 hospitals by June 1.",
        "body": "",
        "importance": "normal",
        "is_read": False,
        "has_attachments": False,
    },
    {
        "id": "demo-019",
        "subject": "ESCALATION: Providence CIO raising concerns about project delays",
        "from": "vp-customersuccess@cisco.com",
        "from_name": "VP Customer Success",
        "received": _ts(0.7),
        "body_preview": "FYI — Providence's CIO Dr. Sarah Nguyen raised concerns directly with our SVP about the telehealth Phase 2 delays. She mentioned competitor alternatives. This is a $4.2M account at risk. We need a recovery plan by EOD tomorrow. Loop in engineering leads and PM for an executive bridge call.",
        "body": "",
        "importance": "high",
        "is_read": False,
        "has_attachments": False,
    },
    {
        "id": "demo-020",
        "subject": "Providence Health — Q4 expansion opportunity (8 new hospitals)",
        "from": "sarah.chen@cisco.com",
        "from_name": "Sarah Chen",
        "received": _ts(7.0),
        "body_preview": "Good news amidst the chaos — Providence wants to discuss expanding to 8 additional hospitals in Q4 if we land Phase 2 successfully. Potential $2.8M upsell. But this is contingent on resolving the current deployment issues. Adding this to the QBR deck.",
        "body": "",
        "importance": "normal",
        "is_read": True,
        "has_attachments": False,
    },
    # ── Internal Emails ──
    {
        "id": "demo-003",
        "subject": "Action Required: Complete mandatory security training by May 30",
        "from": "infosec-training@cisco.com",
        "from_name": "InfoSec Training",
        "received": _ts(6.0),
        "body_preview": "This is a reminder that all employees must complete the annual security awareness training by May 30, 2025. Failure to complete will result in VPN access suspension. Login to CiscoU to complete your modules. You have 3 of 5 modules remaining.",
        "body": "",
        "importance": "normal",
        "is_read": True,
        "has_attachments": False,
    },
    {
        "id": "demo-004",
        "subject": "FYI: New AI Coding Assistant policy — effective June 1",
        "from": "it-governance@cisco.com",
        "from_name": "IT Governance",
        "received": _ts(8.0),
        "body_preview": "Effective June 1st, all use of AI coding assistants must comply with the updated Acceptable Use Policy. Key changes: (1) No proprietary code in public LLMs, (2) Approved tools list updated, (3) Code review required for AI-generated code in production. Full policy attached.",
        "body": "",
        "importance": "normal",
        "is_read": True,
        "has_attachments": True,
    },
    {
        "id": "demo-005",
        "subject": "Meeting invite: Agent Factory — Weekly Standup",
        "from": "raj.patel@cisco.com",
        "from_name": "Raj Patel",
        "received": _ts(3.0),
        "body_preview": "Hi all, adding the recurring weekly standup for the Agent Factory initiative. Every Tuesday at 10am PT. Agenda: progress updates, blockers, and demo slots. First session this week — please come with your top-3 priorities for the sprint.",
        "body": "",
        "importance": "normal",
        "is_read": False,
        "has_attachments": False,
    },
    {
        "id": "demo-006",
        "subject": "Cisco Insider Newsletter — May Edition",
        "from": "newsletter@cisco.com",
        "from_name": "Cisco Insider",
        "received": _ts(14.0),
        "body_preview": "This month: CEO keynote recap from Cisco Live, new hybrid work benefits, employee spotlight on the AppDynamics team, and the latest from the Innovation Challenge winners. Plus: summer intern program kicks off next week!",
        "body": "",
        "importance": "low",
        "is_read": True,
        "has_attachments": False,
    },
    {
        "id": "demo-007",
        "subject": "Re: Can we sync on the Airtable automation architecture?",
        "from": "lisa.wong@cisco.com",
        "from_name": "Lisa Wong",
        "received": _ts(4.5),
        "body_preview": "Hey! I looked at your Airtable setup for the agent tracking dashboard and I think we can simplify the automation. Instead of 3 separate Zaps, we could use a single Airtable Automation with scripting. Free tomorrow at 2pm to whiteboard? I'll bring the architecture sketch.",
        "body": "",
        "importance": "normal",
        "is_read": False,
        "has_attachments": False,
    },
    {
        "id": "demo-008",
        "subject": "Your Amazon order has shipped!",
        "from": "shipment-tracking@amazon.com",
        "from_name": "Amazon.com",
        "received": _ts(10.0),
        "body_preview": "Your order #114-7829463-2847362 has shipped! Estimated delivery: May 24. Track your package at amazon.com/orders. Items: USB-C Hub, Mechanical Keyboard.",
        "body": "",
        "importance": "normal",
        "is_read": True,
        "has_attachments": False,
    },
    {
        "id": "demo-009",
        "subject": "Expense report EXP-2847 approved",
        "from": "concur-noreply@cisco.com",
        "from_name": "Concur",
        "received": _ts(18.0),
        "body_preview": "Your expense report EXP-2847 for $342.50 (Team offsite lunch, client meeting Uber) has been approved by your manager and submitted for payment. Expected deposit: within 5 business days.",
        "body": "",
        "importance": "normal",
        "is_read": True,
        "has_attachments": False,
    },
    {
        "id": "demo-010",
        "subject": "EXTERNAL: Exclusive offer — 70% off premium business tools!",
        "from": "deals@totally-legit-saas.biz",
        "from_name": "Premium Business Tools",
        "received": _ts(12.0),
        "body_preview": "CONGRATULATIONS! You've been selected for an exclusive 70% discount on our premium AI-powered business suite. Click here to claim your offer before it expires! This is a limited-time deal for Cisco employees only. Act now!",
        "body": "",
        "importance": "normal",
        "is_read": False,
        "has_attachments": False,
    },
    {
        "id": "demo-012",
        "subject": "REMINDER (3rd): Complete mandatory security training — deadline in 8 days",
        "from": "infosec-training@cisco.com",
        "from_name": "InfoSec Training",
        "received": _ts(1.5),
        "body_preview": "FINAL REMINDER: This is your 3rd notification. You still have 3 of 5 modules remaining. Deadline: May 30. Non-completion WILL result in VPN access suspension effective June 1. Your manager has been CC'd on this reminder. Complete training at CiscoU immediately.",
        "body": "",
        "importance": "high",
        "is_read": False,
        "has_attachments": False,
    },
    {
        "id": "demo-013",
        "subject": "Re: Can we sync on the Airtable automation architecture? (bumping this)",
        "from": "lisa.wong@cisco.com",
        "from_name": "Lisa Wong",
        "received": _ts(1.2),
        "body_preview": "Bumping this again — I blocked out 2pm tomorrow on your calendar for the Airtable architecture whiteboard. I also looped in Raj since the Agent Factory tracking board is related. Can you confirm you'll be there? I've already sketched the new automation flow.",
        "body": "",
        "importance": "normal",
        "is_read": False,
        "has_attachments": True,
    },
    {
        "id": "demo-015",
        "subject": "Re: Agent Factory — Weekly Standup — action items from Tuesday",
        "from": "raj.patel@cisco.com",
        "from_name": "Raj Patel",
        "received": _ts(0.8),
        "body_preview": "Notes from today's standup: (1) You own the email triage agent demo for next week, (2) Lisa is taking point on Airtable automation, (3) Security review checklist due Friday. Can you confirm your demo slot? Also, I noticed you weren't on the call — everything OK?",
        "body": "",
        "importance": "normal",
        "is_read": False,
        "has_attachments": False,
    },
]
