"""Data models for the Communication Intelligence Agent."""

from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
from enum import Enum


class SourceType(str, Enum):
    WEBEX_CHAT = "webex_chat"
    WEBEX_MEETING_TRANSCRIPT = "webex_meeting_transcript"
    EMAIL = "email"


class ConversationType(str, Enum):
    CUSTOMER = "customer"
    INTERNAL = "internal"
    UNKNOWN = "unknown"


class Priority(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class Participant(BaseModel):
    """Represents a conversation participant."""
    email: str
    display_name: Optional[str] = None
    is_internal: bool = False
    organization: Optional[str] = None


class Message(BaseModel):
    """Represents a single message from any source."""
    id: str
    source_type: SourceType
    source_id: str  # Room ID, meeting ID, or email thread ID
    sender: Participant
    content: str
    timestamp: datetime
    has_attachments: bool = False
    attachment_names: List[str] = Field(default_factory=list)
    is_direct_message: bool = False
    mentioned_people: List[str] = Field(default_factory=list)


class Conversation(BaseModel):
    """Represents a conversation (Webex room, meeting, or email thread)."""
    id: str
    source_type: SourceType
    title: str
    conversation_type: ConversationType = ConversationType.UNKNOWN
    participants: List[Participant] = Field(default_factory=list)
    messages: List[Message] = Field(default_factory=list)
    created_at: Optional[datetime] = None
    last_activity: Optional[datetime] = None
    
    # Derived fields
    customer_name: Optional[str] = None
    external_participants: List[Participant] = Field(default_factory=list)
    
    @property
    def message_count(self) -> int:
        return len(self.messages)
    
    @property
    def full_text(self) -> str:
        """Concatenate all messages for analysis."""
        return "\n".join([
            f"[{m.timestamp.isoformat()}] {m.sender.display_name or m.sender.email}: {m.content}"
            for m in sorted(self.messages, key=lambda x: x.timestamp)
        ])


class ActionItem(BaseModel):
    """Represents an extracted action item."""
    id: str
    description: str
    assignee: Optional[str] = None
    due_date: Optional[datetime] = None
    due_date_reasoning: Optional[str] = None
    priority: Priority = Priority.MEDIUM
    priority_reasoning: Optional[str] = None
    source_conversation_id: str
    source_conversation_title: str
    source_type: SourceType
    conversation_type: ConversationType
    customer_name: Optional[str] = None
    extracted_from_text: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Context
    related_participants: List[str] = Field(default_factory=list)
    keywords_matched: List[str] = Field(default_factory=list)


class MeetingTranscript(BaseModel):
    """Represents a Webex meeting transcript."""
    meeting_id: str
    title: str
    start_time: datetime
    end_time: Optional[datetime] = None
    duration_minutes: Optional[int] = None
    host: Participant
    participants: List[Participant] = Field(default_factory=list)
    transcript_segments: List[dict] = Field(default_factory=list)
    
    @property
    def full_transcript(self) -> str:
        """Get the full transcript as text."""
        return "\n".join([
            f"[{seg.get('timestamp', '')}] {seg.get('speaker', 'Unknown')}: {seg.get('text', '')}"
            for seg in self.transcript_segments
        ])


class Email(BaseModel):
    """Represents an email message."""
    id: str
    subject: str
    sender: Participant
    recipients: List[Participant] = Field(default_factory=list)
    cc: List[Participant] = Field(default_factory=list)
    body_text: str
    body_html: Optional[str] = None
    received_at: datetime
    has_attachments: bool = False
    attachment_names: List[str] = Field(default_factory=list)
    conversation_id: Optional[str] = None
    is_reply: bool = False
    importance: str = "normal"


class AgentReport(BaseModel):
    """Final report generated by the agent."""
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    lookback_days: int
    
    # Summary counts
    total_conversations: int = 0
    customer_conversations: int = 0
    internal_conversations: int = 0
    total_messages: int = 0
    total_emails: int = 0
    total_meeting_transcripts: int = 0
    
    # Extracted data
    action_items: List[ActionItem] = Field(default_factory=list)
    
    # Grouped by customer
    actions_by_customer: dict = Field(default_factory=dict)
    actions_by_priority: dict = Field(default_factory=dict)
    
    @property
    def high_priority_count(self) -> int:
        return len([a for a in self.action_items if a.priority == Priority.HIGH])
    
    @property
    def overdue_count(self) -> int:
        now = datetime.utcnow()
        return len([a for a in self.action_items if a.due_date and a.due_date < now])
