#!/usr/bin/env python3
"""Morning briefing — email digest + calendar placeholder → combined markdown."""

from __future__ import annotations

import argparse
import os
import smtplib
import sys
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

WORKBENCH_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(WORKBENCH_ROOT / "python"))

from orchestration.agent_bridge import (  # noqa: E402
    agt001_digest_markdown,
    calendar_placeholder,
    communication_scan_markdown,
    flerken_digest_markdown,
    status_report_markdown,
)
from orchestration.paths import MORNING_BRIEFING_DIR  # noqa: E402


def _load_dotenv() -> None:
    env_path = WORKBENCH_ROOT / ".env"
    if not env_path.is_file():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def build_briefing(
    *,
    dry_run: bool,
    include_status: bool,
    include_communication: bool,
) -> str:
    today = date.today().isoformat()
    parts = [
        f"# Morning briefing — {today}",
        "",
        f"_Generated by delivery-workbench `morning-briefing.py`"
        f"{' (dry-run)' if dry_run else ''}_",
        "",
    ]

    if os.getenv("MS_CLIENT_ID"):
        email = agt001_digest_markdown(dry_run=dry_run)
    else:
        email = flerken_digest_markdown(demo=dry_run or not os.getenv("OPENAI_API_KEY"), dry_run=dry_run)
    parts.append(email.markdown)

    cal = calendar_placeholder()
    parts.append(cal.markdown)

    if include_communication:
        comm = communication_scan_markdown(dry_run=dry_run)
        parts.append(comm.markdown)

    if include_status:
        status = status_report_markdown(dry_run=dry_run)
        parts.append(status.markdown)

    parts.append(
        "---\n\n"
        "_Next: review urgent items, confirm calendar, run status-report workflow before steering._\n"
    )
    return "\n".join(parts)


def write_briefing(content: str, run_date: date | None = None) -> Path:
    run_date = run_date or date.today()
    out_dir = MORNING_BRIEFING_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{run_date.isoformat()}.md"
    path.write_text(content, encoding="utf-8")
    return path


def send_email(content: str, subject: str) -> None:
    host = os.getenv("SMTP_HOST")
    port = int(os.getenv("SMTP_PORT", "587"))
    user = os.getenv("SMTP_USER")
    password = os.getenv("SMTP_PASSWORD")
    mail_from = os.getenv("SMTP_FROM") or user
    mail_to = os.getenv("SMTP_TO")

    missing = [k for k, v in [
        ("SMTP_HOST", host),
        ("SMTP_USER", user),
        ("SMTP_PASSWORD", password),
        ("SMTP_TO", mail_to),
    ] if not v]
    if missing:
        raise SystemExit(f"Missing SMTP config: {', '.join(missing)} (set in .env)")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = mail_from or user
    msg["To"] = mail_to
    msg.attach(MIMEText(content, "plain", "utf-8"))

    with smtplib.SMTP(host, port, timeout=30) as server:
        server.starttls()
        server.login(user, password)
        server.sendmail(msg["From"], [mail_to], msg.as_string())


def main() -> int:
    parser = argparse.ArgumentParser(description="Build morning briefing markdown")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Use mock/placeholder data; no live Graph, Webex, or LLM calls",
    )
    parser.add_argument(
        "--email",
        action="store_true",
        help="Send briefing via SMTP (requires SMTP_* in .env)",
    )
    parser.add_argument(
        "--status-report",
        action="store_true",
        help="Append status-report-agent section",
    )
    parser.add_argument(
        "--communication-scan",
        action="store_true",
        help="Append communication-agent section",
    )
    args = parser.parse_args()

    _load_dotenv()
    content = build_briefing(
        dry_run=args.dry_run,
        include_status=args.status_report,
        include_communication=args.communication_scan,
    )
    out_path = write_briefing(content)
    print(f"Wrote {out_path}")

    if args.email:
        subject = f"Morning briefing — {date.today().isoformat()}"
        send_email(content, subject)
        print(f"Emailed to {os.getenv('SMTP_TO')}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
